name: Code Check

on:
  push:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run HTML Linter
        run: npm run lint:html

      - name: Run CSS Linter
        run: npm run lint:css

      - name: Run JavaScript Linter
        run: npm run lint:js
